WhereToStudy/Controllers/DeliveriesController.cs
using Warehouse.ViewModels;
using Warehouse.vModel;
using Warehouse.vServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Warehouse.Controllers
{
    public class DeliveriesController : Controller
    {

        public AddEditDeleteService addEditDeleteService = new AddEditDeleteService();
        // GET: Deliveries
        public ActionResult Index()
        {
            var user = Session["User"] as User;
            if (user == null)
                return RedirectToAction("Login", "User");
            else
            {
                var items = new Warehouse.ViewModels.Item()
                {
                    Id = 1,
                    Price = 0,
                    Quantity = 0,
                    SalePrice = 0,
                    TypeId = 1
                };
                var vm = new SaleViewModel()
                {
                    Items = new List<ViewModels.Item>()
                {
                    new ViewModels.Item()
                    {
                        Id = 1,
                Price = 0,
                Quantity = 0,
                SalePrice = 0,
                TypeId = 1
                    }
                }

                };

                return View(vm);
            }
        }

        [HttpPost]
        public ActionResult Index(FormCollection formData)
        {
            var items = new List<vModel.Item>();

            var itemsToDelete = new List<vModel.Item>();
            var items2 = new List<vModel.Item>();
            var deliveries = new List<Operation>();
            var realItems = new List<vModel.Item>();
            for (int i = 0; i < ((formData.Count - 1) / 2); i++)
            {

                int.TryParse(formData["Items[" + i + "].Quantity"], out int qtty);
                items.Add(new vModel.Item()
                {
                    Name = formData["Items[" + i + "].Name"],
                    Quantity = qtty
                });
                itemsToDelete.Add(new vModel.Item()
                {
                    Name = formData["Items[" + i + "].Name"],
                    Quantity = qtty
                });
            }
            var date = DateTime.Now;
            items2 = items;

            for (int i = 0; i < items2.Count; i++)
            {
                var item = addEditDeleteService.GetItem(int.Parse(items2[i].Name));
                items2[i] = item;
            }

                addEditDeleteService.InsertOperation(new Operation()
            {
                Date = date,
                PartnerId = 0,
                Amount = items2.Sum(i => i.Quantity * i.Price),
                OperationTypeId = 2
                });

            var operationId = addEditDeleteService.GetOperations().LastOrDefault().Id;

            foreach (var i in itemsToDelete)
            {
                var item = addEditDeleteService.GetItem(int.Parse(i.Name));
                addEditDeleteService.InsertOperationDetail(new OperationDetail()
                {
                    ItemId = item.Id,
                    OperationId = operationId,
                    Quantity = i.Quantity,
                    SalePrice = item.SalePrice,
                    RowSum = item.SalePrice * i.Quantity
                });

                item.Quantity += i.Quantity;

                addEditDeleteService.UpdateItem(item);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {
            var phones = new List<Phone>();
            phones.Add(new Phone()
            {
                Number = "2465452",
                Type = Phone.Types.Business
            });
            phones = new List<Phone>();
            phones.Add(new Phone()
            {
                Number = "2323",
                Type = Phone.Types.Cell
            });
            var vm = new EmployeeViewModel();
            vm.Name = "Gosho";
            vm.Phones.AddRange(phones);


            return View(vm);
        }

        [HttpPost]
        public ActionResult Create(FormCollection formData)
        {
            string name = formData["Name"];
            string phones0Type = formData["Phones[0].Type"];
            string phones1Number = formData["Phones[0].Number"];
            return RedirectToAction("Index");
        }


        public ActionResult ItemsDeliveries()
        {
            var user = Session["User"] as User;
            if (user == null)
                return RedirectToAction("Login", "User");
            else
            {          
                return View();
            }
        }

        [HttpPost]
        public ActionResult ItemsDeliveries(int id = 0)
        {
            var items = new List<vModel.Item>();
            var deliveries = new List<Operation>();
            var realItems = new List<vModel.Item>();
            //for (int i = 0; i < ((formData.Count - 1) / 2); i++)
            //{
            //    items.Add(new vModel.Item()
            //    {
            //        Name = formData["Items[" + i + "].Name"],
            //        Quantity = int.Parse(formData["Items[" + i + "].Quantity"])
            //    });
            //}
            var date = DateTime.Now;

            addEditDeleteService.InsertOperation(new Operation()
            {
                Date = date,
                PartnerId = 0,
                Amount = items.Sum(i => i.Quantity * i.Price),
                OperationTypeId = 2
            });

            foreach (var i in items)
            {
                // var quantity = items.FirstOrDefault(m => m.Name == i.Name).Quantity;
                
                var item = addEditDeleteService.GetItem(int.Parse(i.Name));
                item.Quantity += i.Quantity;

                addEditDeleteService.UpdateItem(item);
            }

            return RedirectToAction("Index");
        }

    }
}

WhereToStudy/Controllers/ItemsReportController.cs
using Warehouse.ViewModels;
using Warehouse.vModel;
using Warehouse.vServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WhereToStudy.Controllers
{
    public class ItemsReportController : Controller
    {
        public AddEditDeleteService addEditDeleteService = new AddEditDeleteService();
        // GET: ItemsReport
        public ActionResult Items()
        {
            var user = Session["User"] as User;
            if (user == null)
                return RedirectToAction("Login", "User");
            else
            {
                var vm = new SaleReportViewModel();
                var date = DateTime.Now;
                var sales = addEditDeleteService.GetOperationsByDate(date).Where(p => p.OperationTypeId == 1).ToList();
                vm.Items = new List<Warehouse.vModel.Item>();

                foreach (var sale in sales)
                {
                    sale.OperationDetails = addEditDeleteService.GetOperationDetail(sale.Id);
                    foreach (var detail in sale.OperationDetails)
                    {
                        var item = addEditDeleteService.GetItem(detail.ItemId);
                        item.Quantity = detail.Quantity;
                        item.Date = sale.Date;
                        vm.Items.Add(item);
                    }
                }
                vm.Date = date;
                return View(vm);
            }
        }

        [HttpPost]
        public ViewResult Items(string sortOrder, DateTime? searchDate = null)
        {
            if (!searchDate.HasValue)
                searchDate = DateTime.Now;

            var vm = new SaleReportViewModel();
            var sales = addEditDeleteService.GetOperationsByDate(searchDate).Where(p => p.OperationTypeId == 1).ToList();
            vm.Items = new List<Warehouse.vModel.Item>();

            vm.Date = searchDate;
            if (sales.Count < 1)
            {
                return View(vm);
            }

            foreach (var sale in sales)
            {
                sale.OperationDetails = addEditDeleteService.GetOperationDetail(sale.Id);
                foreach (var detail in sale.OperationDetails)
                {
                    var item = addEditDeleteService.GetItem(detail.ItemId);
                    item.Quantity = detail.Quantity;
                    item.Date = sale.Date;
                    vm.Items.Add(item);
                }
            }
            vm.Date = searchDate;
            return View(vm);
        }

        public ActionResult IndexName()
        {
            var items = addEditDeleteService.GetItems();
            return View("Items", items.OrderBy(m => m.Name));
        }

        public ActionResult IndexQuantity()
        {
            var items = addEditDeleteService.GetItems();
            return View("Items", items.OrderBy(m => m.Quantity));
        }



        public ActionResult ItemsSaleReport()
        {
            var user = Session["User"] as User;
            if (user == null)
                return RedirectToAction("Login", "User");
            else
            {
                return View();
            }
        }

        [HttpPost]
        public ViewResult ItemsSaleReport(string sortOrder, int id = 0)
        {
            var sortItem = addEditDeleteService.GetItem(id);

            var vm = new SaleReportViewModel();
            var operation = new List<Operation>();


            var sales = addEditDeleteService.GetOperations();
            if (sortItem != null)
            {

                foreach (var sale in sales)
                {
                    if (sortItem.Id != 0)
                        sale.OperationDetails = addEditDeleteService.GetOperationDetail(sale.Id).Where(p => p.ItemId == sortItem.Id).ToList();
                    else
                        sale.OperationDetails = addEditDeleteService.GetOperationDetail(sale.Id);
                    operation.Add(sale);
                }

                vm.Items = new List<Warehouse.vModel.Item>();

                vm.Item = new Warehouse.ViewModels.Item() { Id = sortItem.Id, Price = sortItem.Price, Quantity = sortItem.Quantity, SalePrice = sortItem.SalePrice, TypeId = sortItem.TypeId };
                if (sales.Count() < 1)
                {
                    return View(vm);
                }

                //foreach (var sale in sales)
                //{
                //    var item = addEditDeleteService.GetItem(sale.ItemId);
                //    item.Quantity = sale.Quantity;
                //    item.Date = sale.Date;
                //    vm.Items.Add(item);
                //}
            }

            foreach (var sale in operation)
            {
                foreach (var det in sale.OperationDetails)
                {
                    var item = addEditDeleteService.GetItem(det.ItemId);
                    item.Quantity = det.Quantity;
                    item.Date = sale.Date;
                    vm.Items.Add(item);
                }
            }

            return View(vm);
        }
    }
}

WhereToStudy/Controllers/SalesController.cs
using Warehouse.ViewModels;
using Warehouse.vModel;
using Warehouse.vServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Warehouse.Controllers
{
    public class SalesController : Controller
    {

        public AddEditDeleteService addEditDeleteService = new AddEditDeleteService();
        // GET: Sales
        public ActionResult Index()
        {
            //var items = new Warehouse.ViewModels.Item()
            //{
            //    Id = 1,
            //    Price = 0,
            //    Quantity = 0,
            //    SalePrice = 0,
            //    TypeId = 1
            //};
            var user = Session["User"] as User;
            if (user == null)
                return RedirectToAction("Login", "User");
            else
            {

                var vm = new SaleViewModel()
                {
                    Items = new List<ViewModels.Item>()
                {
                    new ViewModels.Item()
                    {
                        Id = 1,
                Price = 0,
                Quantity = 0,
                SalePrice = 0,
                TypeId = 1
                    }
                }

                };

                return View(vm);
            }
        }

        [HttpPost]
        public ActionResult Index(FormCollection formData)
        {
            var items = new List<vModel.Item>();
            var deliveries = new List<Operation>();
            var realItems = new List<vModel.Item>();
            for (int i = 0; i < ((formData.Count - 1) / 2); i++)
            {
                int.TryParse(formData["Items[" + i + "].Quantity"],out int qtty);
                items.Add(new vModel.Item()
                {
                    Name = formData["Items[" + i + "].Name"],
                    Quantity = qtty
                });
            }
            var date = DateTime.Now;
            var clientId = Session["Client"] != null ? Session["Client"].ToString() : null;
            int clienntId = 0;
            if (clientId != null)
                int.TryParse(clientId, out clienntId);

            foreach (var i in items)
            {
                //addEditDeleteService.InsertSale(new Sales()
                //{
                //    ItemId = int.Parse(i.Name),
                //    Date = date,
                //    Quantity = i.Quantity,
                //    ClientId = clienntId
                //});
                var item = addEditDeleteService.GetItem(int.Parse(i.Name));
                item.Quantity = i.Quantity;
                AddToCart(item);
                //item.Quantity -= i.Quantity;
                //addEditDeleteService.UpdateItem(item);
            }
            Session.Remove("Client");
            return RedirectToAction("Cart", "ShoppingCart");
        }

        public void AddToCart(vModel.Item item)
        {
            List<vModel.Item> cart = new List<vModel.Item>();
            if ((List<vModel.Item>)Session["cart"] != null)
                cart = (List<vModel.Item>)Session["cart"];

            cart.Add(item);
            Session["cart"] = cart;
            
        }

        [HttpPost]
        public ActionResult AddClient()
        {

            return PartialView("_Clients");
        }


        [HttpPost]
        public void AddClientToSession(Client client)
        {
            Session["Client"] = client.Id;

        }
        //[HttpGet]
        //public ActionResult Create()
        //{
        //    var phones = new List<Phone>();
        //    phones.Add(new Phone()
        //    {
        //        Number = "2465452",
        //        Type = Phone.Types.Business
        //    });
        //    phones = new List<Phone>();
        //    phones.Add(new Phone()
        //    {
        //        Number = "2323",
        //        Type = Phone.Types.Cell
        //    });
        //    var vm = new EmployeeViewModel();
        //    vm.Name = "Gosho";
        //    vm.Phones.AddRange(phones);


        //    return View(vm);
        //}

        //[HttpPost]
        //public ActionResult Create(FormCollection formData)
        //{
        //    string name = formData["Name"];
        //    string phones0Type = formData["Phones[0].Type"];
        //    string phones1Number = formData["Phones[0].Number"];
        //    return RedirectToAction("Index");
        //}



    }
}

WhereToStudy/Views/Shared/_Layout.cshtml
@using Warehouse.vModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">

            </div>
            <div id="mySidenav" class="sidenav">

                @* <a href="#" id="contact"></a>*@
                <a href="@Url.Action("Index", "Home")" id="about">Начало</a>
                <a href="@Url.Action("ClientsReport", "ClientReport")" id="blog">Справка партньори</a>
                <a href="@Url.Action("Index", "ClientReport")" id="projects">Справка продажба по партньори</a>
                <a href="@Url.Action("Index", "DeliveriesReport")" id="contact">Справка по доставки</a>
                <a href="@Url.Action("Items", "ItemsReport")" id="con">Справка по продажби</a>
                <a href="@Url.Action("ItemsSaleReport", "ItemsReport")" id="conn">Справка по продажби по артикул</a>
                <a href="@Url.Action("ItemsDeliveries", "DeliveriesReport")" id="con3">Справка по доставки по артикул</a>

            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li> </li>
                    <li>@Html.ActionLink("Продажба", "Index", "Sales")</li>
                    <li>@Html.ActionLink("Доставка", "Index", "Deliveries")</li>
                    <li>@Html.ActionLink("Наличност", "Index", "Availability")</li>


                    <li class="dropdown">
                        @if (User != null && User.Identity.IsAuthenticated && User.IsAdmin)
                        {
                            <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Добави<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Категория", "AddType", "AddEditDelete")</li>
                                <li>@Html.ActionLink("Артикул", "AddBook", "AddEditDelete")</li>
                                <li>@Html.ActionLink("Клиент", "AddClient", "AddEditDelete")</li>
                                <li>@Html.ActionLink("Група", "AddGroup", "AddEditDelete")</li>
                                <li>@Html.ActionLink("Тип на плащане", "AddPaymentType", "AddEditDelete")</li>
                                <li>@Html.ActionLink("Тип на операция", "AddOperationType", "AddEditDelete")</li>
                            </ul>
                        }

                    <li class="dropdown">
                        @if (User != null && User.Identity.IsAuthenticated && User.IsAdmin)
                        {
                            <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Редактирай\Премахни<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Категория", "DeleteType", "AddEditDelete")</li>
                                <li>@Html.ActionLink("Артикул", "DeleteBook", "AddEditDelete")</li>
                                <li>@Html.ActionLink("Клиент", "DeleteClient", "AddEditDelete")</li>
                                <li>@Html.ActionLink("Група", "DeleteGroup", "AddEditDelete")</li>
                                <li>@Html.ActionLink("Тип на плащане", "DeletePaymentType", "AddEditDelete")</li>
                                <li>@Html.ActionLink("Тип на операция", "DeleteOperationType", "AddEditDelete")</li>
                            </ul>

                        <li>@Html.ActionLink("Потребители", "EditUserRoles", "User")</li>
                    }

                        @if (User != null && User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Моят профил", "Index", "Profile")</li>
                            <li>@Html.ActionLink("Изход", "Logout", "User")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Вход", "Login", "User")</li>
                            <li>@Html.ActionLink("Регистрация", "Registration", "User")</li>
                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container body-content">

            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/custom")
        @RenderSection("scripts", required: false)

        <script>
            $("#menu-toggle").click(function (e) {
                e.preventDefault();
                $("#wrapper").toggleClass("toggled");
            });
        </script>
    </body>
</html>


<style>
    #mySidenav a {
        position: absolute; /* Position them relative to the browser window */
        left: -120px; /* Position them outside of the screen */
        transition: 0.3s; /* Add transition on hover */
        padding: 15px; /* 15px padding */
        width: 150px; /* Set a specific width */
        text-decoration: none; /* Remove underline */
        font-size: 17px; /* Increase font size */
        color: white; /* White text color */
        border-radius: 0 5px 5px 0; /* Rounded corners on the top right and bottom right side */
    }

        #mySidenav a:hover {
            left: 0; /* On mouse-over, make the elements appear as they should */
        }

    /* The about link: 20px from the top with a green background */
    #about {
        top: 20px;
        background-color: #4CAF50;
    }

    #blog {
        top: 70px;
        background-color: #2196F3; /* Blue */
    }

    #projects {
        top: 135px;
        background-color: #f44336; /* Red */
    }

    #contact {
        top: 220px;
        background-color: #555 /* Light Black */
    }
    #con {
        top: 285px;
        background-color: #cc9900 /* Light Black */
    }
    #conn {
        top: 350px;
        background-color: #800000 /* Light Black */
    }
    #con3 {
        top: 440px;
        background-color: #cc6600 /* Light Black */
    }
</style>